### ISSUE TITLE
Use different queues for ES requests

### ISSUE THREAD

**Issue by To-om** [TheHive-Project/elastic4play#97]
Some operations requires many Elasticsearch requests. They saturate thread pool and connection pool and prevent all other operations to be executed before they are finished.
The aim of this issue is to use the thread pool (execution context) of the caller (not the global one) and create a dedicated connection pool of each one.

**Comment by mback2k** [comment]
I am sorry for hijacking this issue, but it seems like this is causing huge performance issues with Cortex version 3.0.1.

Since this seems to have been fixed on the es6 branch of elastic4play, I would like to kindly ask: would it be possible to get a new Cortex version released that contains these fixes? I cannot migrate to es7 yet and spend a whole day debugging this issue, only to find out that the thread pooling is the root cause.
